### ISSUE TITLE
Precompiled binary

### ISSUE THREAD

**Issue by ghost** [maximmasiutin/TinyWeb#1]
Hi,
On ritlabs website,tinyweb's version stopped at 1.94.

Could you release the 1.95's precompiled binary?

Thanks

**Comment by maximmasiutin** [comment]
Thank you, @ghost, for the suggestion! Could you please review the release https://github.com/maximmasiutin/TinyWeb/releases/tag/v1.95 and if it addresses the issue, close it?

**Comment by sergeevabc** [comment]
@maximmasiutin, consider adding a note to `readme.md` that the root folder should have `index.html` (even an empty one), otherwise the program throws an error upon launch.
